name: Vercel Preview Deployment

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches-ignore:
            - main

jobs:

    Test:
        runs-on: ubuntu-latest
        steps:

            # Checkout the code
            - uses: actions/checkout@v3

            # Set up Python environment
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'  # You can change the version as needed

            # Install dependencies from requirements.txt
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            # Run tests (if applicable)
            - name: Run Tests
              run: |
                pytest  # You can customize this step depending on your test framework

    Deploy-Preview:
        needs: [Test]
        runs-on: ubuntu-latest
        steps:

            # Checkout the code again for deployment
            - uses: actions/checkout@v3

            # Install Vercel CLI for deployment
            - name: Install Vercel CLI
              run: npm install --global vercel

            # Pull Vercel environment information for the preview environment
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            # Deploy the Flask app to Vercel Preview
            - name: Deploy Project Artifacts
              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}   
