name: Vercel Production Deployment

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches:
            - main

jobs:
    Deploy-Production:
        runs-on: ubuntu-latest
        steps:
            # Checkout the code from the repository
            - name: Checkout Repository
              uses: actions/checkout@v3

            # Set up Python environment
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'  # Adjust to the Python version you're using

            # Install dependencies from requirements.txt
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            # Install Vercel CLI
            - name: Install Vercel CLI
              run: npm install --global vercel

            # Pull Vercel environment information
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            # Deploy Project to Vercel (removed --prebuilt)
            - name: Deploy to Vercel
              run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
